In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data = pd.read_excel(r'./使用数据/属性表.xls')
df1 = data[['乡镇场','林木使用权','森林类别','地类','面积亩']]#林地资源现状
df1['面积公顷']=df1['面积亩']/15

In [3]:
print(list(data))

['id', 'geometry', '调查方式', '省', '市', '县', '行政乡', '行政村', '经营单位', '乡镇场', '村分场', '小班号', '细班号', '流域名称', '地貌类型', '平均海拔高', '坡向', '坡位', '坡度', '成土母岩', '土壤名称', '土层厚度', '腐殖质厚度', '植被总盖度', '水土流失类型', '水土流失强度', '土地所有权', '林木所有权', '林木使用权', '面积亩', '地类', '林种', '经营类型', '起源', '优势树种', '平均年龄', '龄组', '多目标经营措施', '轮封', '平均胸径', '平均树高', '郁闭度', '活立木总蓄积', '平差后活立木总蓄积', '林分蓄积', '平差后林分蓄积', '散生蓄积', '平差后散生蓄积', '四旁树蓄积', '平差后四旁树蓄积', '四旁树株数', '杉类占', '松类占', '硬阔类占', '软阔类占', '树种比', '枯立木蓄积', '毛竹株数', '幼龄毛竹株数', '壮龄毛竹株数', '杂竹株数', '工程类别', '造林类型', '公益林事权', '公益林区位类型', '公益林区域名称', '群落结构类型', '林层结构', '树种结构', '病虫害等级', '火灾等级', '其它灾害等级', '森林健康等级', '森林自然度', '人工林生长等级', '天然更新等级', '用材林可及度', '经营措施类型', '大等于5CM亩均株数', '小于5CM亩均株数', '亩平均蓄积', '散生木株数', '宗地号', '森林类别', '交通区位等级', '林地质量等级', '林地保护等级', '土地退化类型', '国家级公益林保护等级', '林带长度', '林带宽度', '林地功能分区', '主体功能区', '变化原因', '变化年度', '变更依据', '土地管理类型', '插花县代码', '公益林关键字', '小班唯一编号', '土地利用现状地类', '经营界限', '生态红线', '说明', '林木生长势', '灌木覆盖度', '灌木平均高', '其它', '重要生态功能区', '土地使用权', '林权权利人', '国家级公益林原保护等级', '是否天保工程区', '是否退耕还林', '新一轮退耕还林年度', '生态区位名称', '界定书编号', '管护协议', '是否符合区划范围标准', '是否已改变林地用途', '处理意向', '自然保护区', '遗产地', '湿地及水库', '五河及源头', '饮用水源', '国家森林公园', '军事禁区', '是否为补充林地', '调查人员', '调查时间', '其他1', '其他2', '调查状态', '评定状态', '天保关键字', '连接字段', '功能区划', '经营区划', '经营类型.1', '生态隔离带']

各类土地面积统计表

In [6]:
grouped_df = df1.groupby(['乡镇场','林木使用权','森林类别','地类']).agg({'面积公顷':np.sum})
grouped_df=grouped_df.unstack()
grouped_df

                      面积公顷                                               \
地类                    111         112         1311      1631       141
乡镇场 林木使用权 森林类别
5   1.0   11.0  110.720000  584.233333    6.513333  0.113333        NaN
          13.0         NaN         NaN         NaN       NaN   3.580000
          31.0   29.606667         NaN         NaN       NaN        NaN
          32.0         NaN         NaN   14.946667       NaN        NaN
          34.0         NaN         NaN         NaN       NaN  22.593333
          41.0         NaN  269.753333         NaN       NaN        NaN
          42.0         NaN         NaN   23.213333       NaN        NaN
    2.0   11.0    7.180000    0.700000    3.033333       NaN        NaN
          32.0         NaN         NaN    9.393333       NaN        NaN
          41.0         NaN    0.913333         NaN       NaN        NaN
    3.0   11.0         NaN    2.660000    9.720000       NaN        NaN
          32.0         NaN         NaN   16.473333       NaN        NaN
          34.0         NaN         NaN         NaN       NaN   5.693333
          41.0         NaN         NaN         NaN       NaN        NaN
          44.0         NaN         NaN         NaN       NaN        NaN
    4.0   31.0   35.533333         NaN         NaN       NaN        NaN
6   1.0   11.0   47.946667  226.053333  172.153333       NaN        NaN
          32.0         NaN         NaN  106.673333       NaN        NaN
          41.0   29.526667   45.173333         NaN       NaN        NaN
    3.0   11.0    5.240000         NaN  252.860000       NaN        NaN
          13.0         NaN         NaN         NaN  0.160000        NaN
          32.0         NaN         NaN   30.293333       NaN        NaN
          34.0         NaN         NaN         NaN       NaN   0.753333


地类                  113   161
乡镇场 林木使用权 森林类别
5   1.0   11.0       NaN   NaN
          13.0       NaN   NaN
          31.0       NaN   NaN
          32.0       NaN   NaN
          34.0       NaN   NaN
          41.0       NaN   NaN
          42.0       NaN   NaN
    2.0   11.0       NaN   NaN
          32.0       NaN   NaN
          41.0       NaN   NaN
    3.0   11.0       NaN   NaN
          32.0       NaN   NaN
          34.0       NaN   NaN
          41.0  1.066667   NaN
          44.0       NaN  3.08
    4.0   31.0       NaN   NaN
6   1.0   11.0       NaN   NaN
          32.0       NaN   NaN
          41.0  2.333333   NaN
    3.0   11.0  0.540000   NaN
          13.0       NaN   NaN
          32.0       NaN   NaN
          34.0       NaN   NaN

In [7]:
grouped_df.to_excel(r'./输出数据/各类土地面积统计表.xls')

附表9 各类森林、林木面积蓄积统计表

In [8]:
df1 = data[['乡镇场','林木使用权','地类','面积亩','活立木总蓄积']]#林地资源现状
df1 = df1[df1['地类'].isin([111,112,113,120])]
df1['面积公顷']=df1['面积亩']/15

   乡镇场  林木使用权   地类    面积亩  活立木总蓄积
0    5    1.0  112  374.2    3610
1    5    1.0  112  180.2    1694
2    5    3.0  141   85.4       0
3    5    1.0  112  265.6    2489
4    5    1.0  112  219.7    2341

In [9]:
df1 = df1[df1['地类'].isin([111,112,113,120])]
df1

     乡镇场  林木使用权   地类    面积亩  活立木总蓄积
0      5    1.0  112  374.2    3610
1      5    1.0  112  180.2    1694
3      5    1.0  112  265.6    2489
4      5    1.0  112  219.7    2341
5      5    1.0  112  194.9    1530
..   ...    ...  ...    ...     ...
308    6    1.0  112  321.2    2023
315    6    1.0  113   35.0      18
328    6    3.0  111   25.7      53
330    6    1.0  111    5.3      16
334    6    1.0  112   89.1     799

[170 rows x 5 columns]

In [10]:
df1['面积公顷']=df1['面积亩']/15

In [11]:
grouped_df = df1.groupby(['乡镇场','林木使用权','地类']).agg({'面积公顷':np.sum,'活立木总蓄积':np.sum})
grouped_df=grouped_df.unstack()
grouped_df

                 面积公顷                         活立木总蓄积
地类                111         112       113      111      112   113
乡镇场 林木使用权
5   1.0    140.326667  853.986667       NaN  16894.0  99356.0   NaN
    2.0      7.180000    1.613333       NaN    962.0    172.0   NaN
    3.0           NaN    2.660000  1.066667      NaN    181.0   8.0
    4.0     35.533333         NaN       NaN   3639.0      NaN   NaN
6   1.0     77.473333  271.226667  2.333333  10408.0  31382.0  18.0
    3.0      5.240000         NaN  0.540000    474.0      NaN   4.0

In [12]:
df2 = data[['乡镇场','林木使用权','地类','四旁树蓄积','散生蓄积','四旁树株数','散生木株数']]#林地资源现状
df2.head(5)

   乡镇场  林木使用权   地类  四旁树蓄积  散生蓄积  四旁树株数  散生木株数
0    5    1.0  112      0     0      0      0
1    5    1.0  112      0     0      0      0
2    5    3.0  141      0     0      0      0
3    5    1.0  112      0     0      0      0
4    5    1.0  112      0     0      0      0

In [13]:
grouped_df1 = df2.groupby(['乡镇场','林木使用权']).agg({'四旁树蓄积':np.sum,'散生蓄积':np.sum,'四旁树株数':np.sum,'散生木株数':np.sum})
grouped_df1

           四旁树蓄积  散生蓄积  四旁树株数  散生木株数
乡镇场 林木使用权
5   1.0        0   332      0   6635
    2.0        0    93      0   1864
    3.0        0   204      0   4089
    4.0        0     0      0      0
6   1.0        0  2086      0  41743
    3.0        0  2117      0  42371

In [14]:
df = pd.merge(grouped_df,grouped_df1,how='outer',on=['乡镇场','林木使用权'])
df

C:\Users\Admin\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:643: UserWarning: merging between different levels can give an unintended result (2 levels on the left,1 on the right)
  warnings.warn(msg, UserWarning)

           (面积公顷, 111)  (面积公顷, 112)  (面积公顷, 113)  (活立木总蓄积, 111)  \
乡镇场 林木使用权
5   1.0     140.326667   853.986667          NaN        16894.0
    2.0       7.180000     1.613333          NaN          962.0
    3.0            NaN     2.660000     1.066667            NaN
    4.0      35.533333          NaN          NaN         3639.0
6   1.0      77.473333   271.226667     2.333333        10408.0
    3.0       5.240000          NaN     0.540000          474.0

           (活立木总蓄积, 112)  (活立木总蓄积, 113)  四旁树蓄积  散生蓄积  四旁树株数  散生木株数
乡镇场 林木使用权
5   1.0          99356.0            NaN      0   332      0   6635
    2.0            172.0            NaN      0    93      0   1864
    3.0            181.0            8.0      0   204      0   4089
    4.0              NaN            NaN      0     0      0      0
6   1.0          31382.0           18.0      0  2086      0  41743
    3.0              NaN            4.0      0  2117      0  42371

In [15]:
df.to_excel(r'./输出数据/各类森林、林木面积蓄积统计表.xls')

附表16. 按起源各林种分树种统计表

In [35]:
df1 = data[['乡镇场','林木使用权','林种','优势树种','地类','龄组','面积亩','活立木总蓄积']]#林地资源现状
df1 = df1[df1['地类'].isin([111,112,113,120])]
df1 = df1[df1['龄组'].isin([11,12,13,14,15])]
df1['面积公顷']=df1['面积亩']/15
df1

     乡镇场  林木使用权     林种   优势树种   地类    龄组    面积亩  活立木总蓄积       面积公顷
0      5    1.0  233.0  630.0  112  12.0  374.2    3610  24.946667
1      5    1.0  112.0  630.0  112  12.0  180.2    1694  12.013333
3      5    1.0  233.0  630.0  112  12.0  265.6    2489  17.706667
4      5    1.0  233.0  630.0  112  12.0  219.7    2341  14.646667
5      5    1.0  111.0  630.0  112  11.0  194.9    1530  12.993333
..   ...    ...    ...    ...  ...   ...    ...     ...        ...
307    6    1.0  111.0  490.0  111  11.0   10.2      50   0.680000
308    6    1.0  233.0  630.0  112  13.0  321.2    2023  21.413333
328    6    3.0  111.0  440.0  111  11.0   25.7      53   1.713333
330    6    1.0  233.0  310.0  111  11.0    5.3      16   0.353333
334    6    1.0  233.0  630.0  112  13.0   89.1     799   5.940000

[167 rows x 9 columns]

In [17]:
df1 = df1[df1['地类'].isin([111,112,113,120])]
df1 = df1[df1['龄组'].isin([11,12,13,14,15])]
df1

     乡镇场  林木使用权     林种   优势树种   地类    龄组    面积亩  活立木总蓄积
0      5    1.0  233.0  630.0  112  12.0  374.2    3610
1      5    1.0  112.0  630.0  112  12.0  180.2    1694
3      5    1.0  233.0  630.0  112  12.0  265.6    2489
4      5    1.0  233.0  630.0  112  12.0  219.7    2341
5      5    1.0  111.0  630.0  112  11.0  194.9    1530
..   ...    ...    ...    ...  ...   ...    ...     ...
307    6    1.0  111.0  490.0  111  11.0   10.2      50
308    6    1.0  233.0  630.0  112  13.0  321.2    2023
328    6    3.0  111.0  440.0  111  11.0   25.7      53
330    6    1.0  233.0  310.0  111  11.0    5.3      16
334    6    1.0  233.0  630.0  112  13.0   89.1     799

[167 rows x 8 columns]

In [18]:
df1['面积公顷']=df1['面积亩']/15

In [19]:
grouped_df = df1.groupby(['乡镇场','林木使用权','林种','优势树种','地类','龄组']).agg({'面积公顷':np.sum,'活立木总蓄积':np.sum})
grouped_df=grouped_df.unstack()
grouped_df=grouped_df.unstack()
grouped_df

                            面积公顷                                     \
龄组                          11.0                   12.0
地类                           111         112        111         112
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0        NaN    1.280000        NaN         NaN
                630.0        NaN   30.493333        NaN   71.886667
          112.0 220.0  12.193333         NaN   2.126667         NaN
                310.0  96.400000         NaN        NaN         NaN
                620.0        NaN    1.593333        NaN         NaN
                630.0        NaN  310.966667        NaN  168.013333
          232.0 310.0        NaN         NaN        NaN         NaN
          233.0 610.0        NaN         NaN        NaN    4.046667
                620.0        NaN         NaN        NaN    2.740000
                630.0        NaN         NaN        NaN  261.420000
    2.0   112.0 310.0   7.180000         NaN        NaN         NaN
                630.0        NaN    0.700000        NaN         NaN
          233.0 610.0        NaN    0.913333        NaN         NaN
    3.0   111.0 610.0        NaN    0.480000        NaN         NaN
          112.0 630.0        NaN    2.180000        NaN         NaN
    4.0   231.0 550.0        NaN         NaN        NaN         NaN
6   1.0   111.0 220.0  12.113333         NaN  23.620000         NaN
                310.0   6.860000         NaN   3.973333         NaN
                490.0   1.380000         NaN        NaN         NaN
                610.0        NaN   17.433333        NaN   27.340000
                620.0        NaN   61.700000        NaN   21.380000
                630.0        NaN    5.833333        NaN   20.133333
          112.0 620.0        NaN         NaN        NaN   42.033333
          233.0 220.0  21.453333         NaN        NaN         NaN
                310.0   0.566667         NaN   7.093333         NaN
                490.0   0.413333         NaN        NaN         NaN
                610.0        NaN    1.133333        NaN    3.153333
                620.0        NaN         NaN        NaN    0.426667
                630.0        NaN         NaN        NaN   13.106667
    3.0   111.0 220.0        NaN         NaN   2.340000         NaN
                310.0   1.186667         NaN        NaN         NaN
                440.0   1.713333         NaN        NaN         NaN

                                                            活立木总蓄积           \
龄组                          13.0                  15.0        11.0
地类                           111        112        111 112     111      112
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0        NaN        NaN        NaN NaN     NaN    194.0
                630.0        NaN        NaN        NaN NaN     NaN   3722.0
          112.0 220.0        NaN        NaN        NaN NaN  1374.0      NaN
                310.0        NaN        NaN        NaN NaN  9974.0      NaN
                620.0        NaN        NaN        NaN NaN     NaN    156.0
                630.0        NaN        NaN        NaN NaN     NaN  35611.0
          232.0 310.0  29.606667        NaN        NaN NaN     NaN      NaN
          233.0 610.0        NaN   1.546667        NaN NaN     NaN      NaN
                620.0        NaN        NaN        NaN NaN     NaN      NaN
                630.0        NaN        NaN        NaN NaN     NaN      NaN
    2.0   112.0 310.0        NaN        NaN        NaN NaN   962.0      NaN
                630.0        NaN        NaN        NaN NaN     NaN     88.0
          233.0 610.0        NaN        NaN        NaN NaN     NaN     84.0
    3.0   111.0 610.0        NaN        NaN        NaN NaN     NaN     18.0
          112.0 630.0        NaN        NaN        NaN NaN     NaN    163.0
    4.0   231.0 550.0        NaN        NaN  35.533333 NaN     NaN      NaN
6   1.0   111.0 220.0        NaN        NaN        NaN NaN  1836.0      NaN
                310.0        NaN        NaN        NaN NaN   636.0      NaN
                490.0        NaN        NaN        NaN NaN   122.0      NaN
                610.0        NaN  30.200000        NaN NaN     NaN   1376.0
                620.0        NaN        NaN        NaN NaN     NaN   8125.0
                630.0        NaN        NaN        NaN NaN     NaN    233.0
          112.0 620.0        NaN        NaN        NaN NaN     NaN      NaN
          233.0 220.0        NaN        NaN        NaN NaN  2233.0      NaN
                310.0        NaN        NaN        NaN NaN    25.0      NaN
                490.0        NaN        NaN        NaN NaN    10.0      NaN
                610.0        NaN        NaN        NaN NaN     NaN     76.0
                620.0        NaN        NaN        NaN NaN     NaN      NaN
                630.0        NaN  27.353333        NaN NaN     NaN      NaN
    3.0   111.0 220.0        NaN        NaN        NaN NaN     NaN      NaN
                310.0        NaN        NaN        NaN NaN   211.0      NaN
                440.0        NaN        NaN        NaN NaN    53.0      NaN


龄组                       12.0             13.0            15.0
地类                        111      112     111     112     111 112
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0     NaN      NaN     NaN     NaN     NaN NaN
                630.0     NaN   6865.0     NaN     NaN     NaN NaN
          112.0 220.0   122.0      NaN     NaN     NaN     NaN NaN
                310.0     NaN      NaN     NaN     NaN     NaN NaN
                620.0     NaN      NaN     NaN     NaN     NaN NaN
                630.0     NaN  20217.0     NaN     NaN     NaN NaN
          232.0 310.0     NaN      NaN  5424.0     NaN     NaN NaN
          233.0 610.0     NaN    487.0     NaN   214.0     NaN NaN
                620.0     NaN    248.0     NaN     NaN     NaN NaN
                630.0     NaN  31642.0     NaN     NaN     NaN NaN
    2.0   112.0 310.0     NaN      NaN     NaN     NaN     NaN NaN
                630.0     NaN      NaN     NaN     NaN     NaN NaN
          233.0 610.0     NaN      NaN     NaN     NaN     NaN NaN
    3.0   111.0 610.0     NaN      NaN     NaN     NaN     NaN NaN
          112.0 630.0     NaN      NaN     NaN     NaN     NaN NaN
    4.0   231.0 550.0     NaN      NaN     NaN     NaN  3639.0 NaN
6   1.0   111.0 220.0  3949.0      NaN     NaN     NaN     NaN NaN
                310.0   183.0      NaN     NaN     NaN     NaN NaN
                490.0     NaN      NaN     NaN     NaN     NaN NaN
                610.0     NaN   3875.0     NaN  3086.0     NaN NaN
                620.0     NaN   3648.0     NaN     NaN     NaN NaN
                630.0     NaN   1510.0     NaN     NaN     NaN NaN
          112.0 620.0     NaN   4056.0     NaN     NaN     NaN NaN
          233.0 220.0     NaN      NaN     NaN     NaN     NaN NaN
                310.0  1414.0      NaN     NaN     NaN     NaN NaN
                490.0     NaN      NaN     NaN     NaN     NaN NaN
                610.0     NaN    444.0     NaN     NaN     NaN NaN
                620.0     NaN     40.0     NaN     NaN     NaN NaN
                630.0     NaN   2091.0     NaN  2822.0     NaN NaN
    3.0   111.0 220.0   210.0      NaN     NaN     NaN     NaN NaN
                310.0     NaN      NaN     NaN     NaN     NaN NaN
                440.0     NaN      NaN     NaN     NaN     NaN NaN

In [36]:
df2 = data[['乡镇场','林木使用权','林种','优势树种','地类','龄组','面积亩','活立木总蓄积']]#林地资源现状
df2 = df2[df2['地类'].isin([1311,1312,1313,132,141,142])]
df2['面积公顷']=df2['面积亩']/15
df2

     乡镇场  林木使用权     林种   优势树种    地类    龄组    面积亩  活立木总蓄积      面积公顷
2      5    3.0  232.0  261.0   141   NaN   85.4       0  5.693333
7      5    3.0  251.0  720.0  1311  33.0   32.9      16  2.193333
8      5    1.0  232.0  261.0   141   NaN  120.7       0  8.046667
9      5    2.0  251.0  720.0  1311  31.0   68.9      34  4.593333
24     5    1.0  112.0  720.0  1311  33.0   35.3      18  2.353333
..   ...    ...    ...    ...   ...   ...    ...     ...       ...
329    6    3.0  111.0  720.0  1311  31.0    5.9       0  0.393333
331    6    1.0  251.0  720.0  1311  31.0    2.4       0  0.160000
332    6    1.0  251.0  720.0  1311  33.0   48.9      24  3.260000
333    6    1.0  251.0  720.0  1311  33.0   17.7       9  1.180000
335    6    1.0  251.0  720.0  1311  33.0   15.2       8  1.013333

[147 rows x 9 columns]

In [21]:
df2 = df2[df2['地类'].isin([1311,1312,1313,132,141,142])]
df2

     乡镇场  林木使用权     林种   优势树种    地类    龄组    面积亩  活立木总蓄积
2      5    3.0  232.0  261.0   141   NaN   85.4       0
7      5    3.0  251.0  720.0  1311  33.0   32.9      16
8      5    1.0  232.0  261.0   141   NaN  120.7       0
9      5    2.0  251.0  720.0  1311  31.0   68.9      34
24     5    1.0  112.0  720.0  1311  33.0   35.3      18
..   ...    ...    ...    ...   ...   ...    ...     ...
329    6    3.0  111.0  720.0  1311  31.0    5.9       0
331    6    1.0  251.0  720.0  1311  31.0    2.4       0
332    6    1.0  251.0  720.0  1311  33.0   48.9      24
333    6    1.0  251.0  720.0  1311  33.0   17.7       9
335    6    1.0  251.0  720.0  1311  33.0   15.2       8

[147 rows x 8 columns]

In [22]:
df2['面积公顷']=df2['面积亩']/15

In [23]:
grouped_df1 = df2.groupby(['乡镇场','林木使用权','林种','优势树种','地类']).agg({'面积公顷':np.sum})
grouped_df1=grouped_df1.unstack()
grouped_df1

                            面积公顷
地类                          141         1311
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 749.0        NaN    4.160000
          112.0 220.0   3.580000         NaN
                720.0        NaN    2.353333
          232.0 261.0  11.426667         NaN
                310.0  11.166667         NaN
          251.0 720.0        NaN   14.946667
                749.0        NaN    9.100000
          252.0 755.0        NaN   14.113333
    2.0   112.0 720.0        NaN    3.033333
          251.0 720.0        NaN    9.393333
    3.0   112.0 720.0        NaN    9.720000
          232.0 261.0   5.693333         NaN
          251.0 720.0        NaN   16.473333
6   1.0   111.0 720.0        NaN  145.740000
                859.0        NaN    1.386667
          112.0 720.0        NaN   25.026667
          251.0 720.0        NaN  106.673333
    3.0   111.0 720.0        NaN  220.680000
                859.0        NaN    8.386667
          112.0 720.0        NaN   23.793333
          232.0 310.0   0.753333         NaN
          251.0 720.0        NaN   30.293333

In [24]:
df = pd.merge(grouped_df,grouped_df1,how='outer',on=['乡镇场','林木使用权','林种','优势树种'])
df

C:\Users\Admin\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:643: UserWarning: merging between different levels can give an unintended result (3 levels on the left,2 on the right)
  warnings.warn(msg, UserWarning)

                       (面积公顷, 11.0, 111)  (面积公顷, 11.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                NaN           1.280000
                630.0                NaN          30.493333
          112.0 220.0          12.193333                NaN
                310.0          96.400000                NaN
                620.0                NaN           1.593333
                630.0                NaN         310.966667
          232.0 310.0                NaN                NaN
          233.0 610.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
    2.0   112.0 310.0           7.180000                NaN
                630.0                NaN           0.700000
          233.0 610.0                NaN           0.913333
    3.0   111.0 610.0                NaN           0.480000
          112.0 630.0                NaN           2.180000
    4.0   231.0 550.0                NaN                NaN
6   1.0   111.0 220.0          12.113333                NaN
                310.0           6.860000                NaN
                490.0           1.380000                NaN
                610.0                NaN          17.433333
                620.0                NaN          61.700000
                630.0                NaN           5.833333
          112.0 620.0                NaN                NaN
          233.0 220.0          21.453333                NaN
                310.0           0.566667                NaN
                490.0           0.413333                NaN
                610.0                NaN           1.133333
                620.0                NaN                NaN
                630.0                NaN                NaN
    3.0   111.0 220.0                NaN                NaN
                310.0           1.186667                NaN
                440.0           1.713333                NaN
5   1.0   111.0 749.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
                749.0                NaN                NaN
          252.0 755.0                NaN                NaN
    2.0   112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
6   1.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 310.0                NaN                NaN
          251.0 720.0                NaN                NaN

                       (面积公顷, 12.0, 111)  (面积公顷, 12.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                NaN                NaN
                630.0                NaN          71.886667
          112.0 220.0           2.126667                NaN
                310.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN         168.013333
          232.0 310.0                NaN                NaN
          233.0 610.0                NaN           4.046667
                620.0                NaN           2.740000
                630.0                NaN         261.420000
    2.0   112.0 310.0                NaN                NaN
                630.0                NaN                NaN
          233.0 610.0                NaN                NaN
    3.0   111.0 610.0                NaN                NaN
          112.0 630.0                NaN                NaN
    4.0   231.0 550.0                NaN                NaN
6   1.0   111.0 220.0          23.620000                NaN
                310.0           3.973333                NaN
                490.0                NaN                NaN
                610.0                NaN          27.340000
                620.0                NaN          21.380000
                630.0                NaN          20.133333
          112.0 620.0                NaN          42.033333
          233.0 220.0                NaN                NaN
                310.0           7.093333                NaN
                490.0                NaN                NaN
                610.0                NaN           3.153333
                620.0                NaN           0.426667
                630.0                NaN          13.106667
    3.0   111.0 220.0           2.340000                NaN
                310.0                NaN                NaN
                440.0                NaN                NaN
5   1.0   111.0 749.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
                749.0                NaN                NaN
          252.0 755.0                NaN                NaN
    2.0   112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
6   1.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 310.0                NaN                NaN
          251.0 720.0                NaN                NaN

                       (面积公顷, 13.0, 111)  (面积公顷, 13.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                NaN                NaN
                630.0                NaN                NaN
          112.0 220.0                NaN                NaN
                310.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
          232.0 310.0          29.606667                NaN
          233.0 610.0                NaN           1.546667
                620.0                NaN                NaN
                630.0                NaN                NaN
    2.0   112.0 310.0                NaN                NaN
                630.0                NaN                NaN
          233.0 610.0                NaN                NaN
    3.0   111.0 610.0                NaN                NaN
          112.0 630.0                NaN                NaN
    4.0   231.0 550.0                NaN                NaN
6   1.0   111.0 220.0                NaN                NaN
                310.0                NaN                NaN
                490.0                NaN                NaN
                610.0                NaN          30.200000
                620.0                NaN                NaN
                630.0                NaN                NaN
          112.0 620.0                NaN                NaN
          233.0 220.0                NaN                NaN
                310.0                NaN                NaN
                490.0                NaN                NaN
                610.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN          27.353333
    3.0   111.0 220.0                NaN                NaN
                310.0                NaN                NaN
                440.0                NaN                NaN
5   1.0   111.0 749.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
                749.0                NaN                NaN
          252.0 755.0                NaN                NaN
    2.0   112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
6   1.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 310.0                NaN                NaN
          251.0 720.0                NaN                NaN

                       (面积公顷, 15.0, 111)  (面积公顷, 15.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                NaN                NaN
                630.0                NaN                NaN
          112.0 220.0                NaN                NaN
                310.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
          232.0 310.0                NaN                NaN
          233.0 610.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
    2.0   112.0 310.0                NaN                NaN
                630.0                NaN                NaN
          233.0 610.0                NaN                NaN
    3.0   111.0 610.0                NaN                NaN
          112.0 630.0                NaN                NaN
    4.0   231.0 550.0          35.533333                NaN
6   1.0   111.0 220.0                NaN                NaN
                310.0                NaN                NaN
                490.0                NaN                NaN
                610.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
          112.0 620.0                NaN                NaN
          233.0 220.0                NaN                NaN
                310.0                NaN                NaN
                490.0                NaN                NaN
                610.0                NaN                NaN
                620.0                NaN                NaN
                630.0                NaN                NaN
    3.0   111.0 220.0                NaN                NaN
                310.0                NaN                NaN
                440.0                NaN                NaN
5   1.0   111.0 749.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
                749.0                NaN                NaN
          252.0 755.0                NaN                NaN
    2.0   112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   112.0 720.0                NaN                NaN
          232.0 261.0                NaN                NaN
          251.0 720.0                NaN                NaN
6   1.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          251.0 720.0                NaN                NaN
    3.0   111.0 720.0                NaN                NaN
                859.0                NaN                NaN
          112.0 720.0                NaN                NaN
          232.0 310.0                NaN                NaN
          251.0 720.0                NaN                NaN

                       (活立木总蓄积, 11.0, 111)  (活立木总蓄积, 11.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                  NaN                194.0
                630.0                  NaN               3722.0
          112.0 220.0               1374.0                  NaN
                310.0               9974.0                  NaN
                620.0                  NaN                156.0
                630.0                  NaN              35611.0
          232.0 310.0                  NaN                  NaN
          233.0 610.0                  NaN                  NaN
                620.0                  NaN                  NaN
                630.0                  NaN                  NaN
    2.0   112.0 310.0                962.0                  NaN
                630.0                  NaN                 88.0
          233.0 610.0                  NaN                 84.0
    3.0   111.0 610.0                  NaN                 18.0
          112.0 630.0                  NaN                163.0
    4.0   231.0 550.0                  NaN                  NaN
6   1.0   111.0 220.0               1836.0                  NaN
                310.0                636.0                  NaN
                490.0                122.0                  NaN
                610.0                  NaN               1376.0
                620.0                  NaN               8125.0
                630.0                  NaN                233.0
          112.0 620.0                  NaN                  NaN
          233.0 220.0               2233.0                  NaN
                310.0                 25.0                  NaN
                490.0                 10.0                  NaN
                610.0                  NaN                 76.0
                620.0                  NaN                  NaN
                630.0                  NaN                  NaN
    3.0   111.0 220.0                  NaN                  NaN
                310.0                211.0                  NaN
                440.0                 53.0                  NaN
5   1.0   111.0 749.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          232.0 261.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
                749.0                  NaN                  NaN
          252.0 755.0                  NaN                  NaN
    2.0   112.0 720.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
    3.0   112.0 720.0                  NaN                  NaN
          232.0 261.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
6   1.0   111.0 720.0                  NaN                  NaN
                859.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
    3.0   111.0 720.0                  NaN                  NaN
                859.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          232.0 310.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN

                       (活立木总蓄积, 12.0, 111)  (活立木总蓄积, 12.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                  NaN                  NaN
                630.0                  NaN               6865.0
          112.0 220.0                122.0                  NaN
                310.0                  NaN                  NaN
                620.0                  NaN                  NaN
                630.0                  NaN              20217.0
          232.0 310.0                  NaN                  NaN
          233.0 610.0                  NaN                487.0
                620.0                  NaN                248.0
                630.0                  NaN              31642.0
    2.0   112.0 310.0                  NaN                  NaN
                630.0                  NaN                  NaN
          233.0 610.0                  NaN                  NaN
    3.0   111.0 610.0                  NaN                  NaN
          112.0 630.0                  NaN                  NaN
    4.0   231.0 550.0                  NaN                  NaN
6   1.0   111.0 220.0               3949.0                  NaN
                310.0                183.0                  NaN
                490.0                  NaN                  NaN
                610.0                  NaN               3875.0
                620.0                  NaN               3648.0
                630.0                  NaN               1510.0
          112.0 620.0                  NaN               4056.0
          233.0 220.0                  NaN                  NaN
                310.0               1414.0                  NaN
                490.0                  NaN                  NaN
                610.0                  NaN                444.0
                620.0                  NaN                 40.0
                630.0                  NaN               2091.0
    3.0   111.0 220.0                210.0                  NaN
                310.0                  NaN                  NaN
                440.0                  NaN                  NaN
5   1.0   111.0 749.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          232.0 261.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
                749.0                  NaN                  NaN
          252.0 755.0                  NaN                  NaN
    2.0   112.0 720.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
    3.0   112.0 720.0                  NaN                  NaN
          232.0 261.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
6   1.0   111.0 720.0                  NaN                  NaN
                859.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN
    3.0   111.0 720.0                  NaN                  NaN
                859.0                  NaN                  NaN
          112.0 720.0                  NaN                  NaN
          232.0 310.0                  NaN                  NaN
          251.0 720.0                  NaN                  NaN

                       (活立木总蓄积, 13.0, 111)  (活立木总蓄积, 13.0, 112)  \
乡镇场 林木使用权 林种    优势树种
5   1.0   111.0 620.0                  NaN                  NaN
                630.0                  NaN                  NaN
          112.0 220.0                  NaN                  NaN
                310.0                  NaN                  NaN

In [25]:
df.to_excel(r'./输出数据/按起源各林种分树种统计表.xls')

附表15 乔木林面积蓄积按龄组统计表

In [37]:
df1 = data[['乡镇场','地类','起源','优势树种','龄组','面积亩','活立木总蓄积']]#林地资源现状
df1 = df1[df1['地类'].isin([111,112])]
df1['面积公顷']=df1['面积亩']/15
df1

     乡镇场   地类    起源   优势树种    龄组    面积亩  活立木总蓄积       面积公顷
0      5  112  11.0  630.0  12.0  374.2    3610  24.946667
1      5  112  11.0  630.0  12.0  180.2    1694  12.013333
3      5  112  11.0  630.0  12.0  265.6    2489  17.706667
4      5  112  11.0  630.0  12.0  219.7    2341  14.646667
5      5  112  11.0  630.0  11.0  194.9    1530  12.993333
..   ...  ...   ...    ...   ...    ...     ...        ...
307    6  111  12.0  490.0  11.0   10.2      50   0.680000
308    6  112  11.0  630.0  13.0  321.2    2023  21.413333
328    6  111  21.0  440.0  11.0   25.7      53   1.713333
330    6  111  12.0  310.0  11.0    5.3      16   0.353333
334    6  112  11.0  630.0  13.0   89.1     799   5.940000

[167 rows x 8 columns]

In [27]:
df1 = df1[df1['地类'].isin([111,112])]
df1

     乡镇场   地类    起源   优势树种    龄组    面积亩  活立木总蓄积
0      5  112  11.0  630.0  12.0  374.2    3610
1      5  112  11.0  630.0  12.0  180.2    1694
3      5  112  11.0  630.0  12.0  265.6    2489
4      5  112  11.0  630.0  12.0  219.7    2341
5      5  112  11.0  630.0  11.0  194.9    1530
..   ...  ...   ...    ...   ...    ...     ...
307    6  111  12.0  490.0  11.0   10.2      50
308    6  112  11.0  630.0  13.0  321.2    2023
328    6  111  21.0  440.0  11.0   25.7      53
330    6  111  12.0  310.0  11.0    5.3      16
334    6  112  11.0  630.0  13.0   89.1     799

[167 rows x 7 columns]

In [28]:
df1['面积公顷']=df1['面积亩']/15

In [29]:
grouped_df1 = df1.groupby(['乡镇场','地类','起源','优势树种','龄组']).agg({'面积公顷':np.sum,'活立木总蓄积':np.sum})
grouped_df1=grouped_df1.unstack()
grouped_df1

                          面积公顷                                     活立木总蓄积  \
龄组                        11.0        12.0       13.0       15.0     11.0
乡镇场 地类  起源   优势树种
5   111 11.0 220.0         NaN    1.180000        NaN        NaN      NaN
        21.0 220.0   12.193333         NaN        NaN        NaN   1374.0
             310.0   96.520000         NaN  29.606667        NaN  10044.0
             550.0         NaN         NaN        NaN  35.533333      NaN
        22.0 310.0    7.060000         NaN        NaN        NaN    892.0
        23.0 220.0         NaN    0.946667        NaN        NaN      NaN
    112 11.0 620.0         NaN    2.740000        NaN        NaN      NaN
             630.0  320.886667  495.813333        NaN        NaN  36779.0
        12.0 630.0         NaN    4.473333        NaN        NaN      NaN
        21.0 610.0         NaN    4.046667        NaN        NaN      NaN
             620.0    1.593333         NaN        NaN        NaN    156.0
        23.0 610.0    1.393333         NaN   1.546667        NaN    102.0
             620.0    1.280000         NaN        NaN        NaN    194.0
             630.0   23.453333    1.033333        NaN        NaN   2805.0
6   111 11.0 220.0   15.286667         NaN        NaN        NaN   2425.0
             310.0    4.640000         NaN        NaN        NaN    567.0
             490.0    0.700000         NaN        NaN        NaN     72.0
        12.0 220.0   18.280000   25.960000        NaN        NaN   1644.0
             310.0    3.973333   11.066667        NaN        NaN    305.0
             490.0    1.093333         NaN        NaN        NaN     60.0
        21.0 440.0    1.713333         NaN        NaN        NaN     53.0
    112 11.0 620.0   12.840000   53.946667        NaN        NaN   2354.0
             630.0         NaN   13.106667  27.353333        NaN      NaN
        12.0 610.0   18.566667   30.493333  30.200000        NaN   1452.0
             620.0   48.860000    9.893333        NaN        NaN   5771.0
             630.0    5.833333   20.133333        NaN        NaN    233.0


龄组                     12.0    13.0    15.0
乡镇场 地类  起源   优势树种
5   111 11.0 220.0     74.0     NaN     NaN
        21.0 220.0      NaN     NaN     NaN
             310.0      NaN  5424.0     NaN
             550.0      NaN     NaN  3639.0
        22.0 310.0      NaN     NaN     NaN
        23.0 220.0     48.0     NaN     NaN
    112 11.0 620.0    248.0     NaN     NaN
             630.0  58489.0     NaN     NaN
        12.0 630.0    177.0     NaN     NaN
        21.0 610.0    487.0     NaN     NaN
             620.0      NaN     NaN     NaN
        23.0 610.0      NaN   214.0     NaN
             620.0      NaN     NaN     NaN
             630.0     58.0     NaN     NaN
6   111 11.0 220.0      NaN     NaN     NaN
             310.0      NaN     NaN     NaN
             490.0      NaN     NaN     NaN
        12.0 220.0   4159.0     NaN     NaN
             310.0   1597.0     NaN     NaN
             490.0      NaN     NaN     NaN
        21.0 440.0      NaN     NaN     NaN
    112 11.0 620.0   6097.0     NaN     NaN
             630.0   2091.0  2822.0     NaN
        12.0 610.0   4319.0  3086.0     NaN
             620.0   1647.0     NaN     NaN
             630.0   1510.0     NaN     NaN

生态公益林分林种蓄积统计表

In [38]:
df1 = data[['乡镇场','公益林事权','林木使用权','林种','面积亩','活立木总蓄积']]#林地资源现状
df1['面积公顷']=df1['面积亩']/15
df1

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     乡镇场  公益林事权  林木使用权     林种    面积亩  活立木总蓄积       面积公顷
0      5    NaN    1.0  233.0  374.2    3610  24.946667
1      5    1.0    1.0  112.0  180.2    1694  12.013333
2      5    NaN    3.0  232.0   85.4       0   5.693333
3      5    NaN    1.0  233.0  265.6    2489  17.706667
4      5    NaN    1.0  233.0  219.7    2341  14.646667
..   ...    ...    ...    ...    ...     ...        ...
331    6    NaN    1.0  251.0    2.4       0   0.160000
332    6    NaN    1.0  251.0   48.9      24   3.260000
333    6    NaN    1.0  251.0   17.7       9   1.180000
334    6    NaN    1.0  233.0   89.1     799   5.940000
335    6    NaN    1.0  251.0   15.2       8   1.013333

[336 rows x 7 columns]

In [31]:
df1['面积公顷']=df1['面积亩']/15

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [32]:
grouped_df1 = df1.groupby(['乡镇场','公益林事权','林木使用权','林种']).agg({'面积公顷':np.sum,'活立木总蓄积':np.sum})
grouped_df1=grouped_df1.unstack()
grouped_df1

                       面积公顷               活立木总蓄积
林种                    111.0       112.0    111.0    112.0
乡镇场 公益林事权 林木使用权
5   1.0   1.0    107.820000  430.286667  10812.0  50568.0
          2.0           NaN   10.913333      NaN   1073.0
          3.0      0.480000   11.900000     18.0    236.0
    2.0   1.0           NaN  167.053333      NaN  16904.0
6   1.0   1.0    134.606667   49.520000  15559.0   2139.0
          3.0      3.893333         NaN     29.0      NaN
    2.0   1.0    244.486667   17.540000  14117.0   2104.0
          3.0    230.953333   23.953333   2160.0    178.0

In [33]:
grouped_df1.to_excel(r'./输出数据/按起源各林种分树种统计表.xls')